### ISSUE TITLE
provided source filename invalid; source file does not exist `foo.html`

### ISSUE THREAD

**Issue by Lanskask** [mike-huls/cythonbuilder#7]
Hi

My repo
[Cython_Experiments](https://github.com/Lanskask/Cython_Experiments)

After I run 
`cythonbuilder build --include-numpy --no-annotation --no-interface --no-cleanup`

I get the following 
```
[cythonbuilder] 09:04:33 cli                  104  build error: move_file] - provided source filename invalid; source file does not exist: /Users/mac/Programming/Cpp_n_Python/Cython/primes_module/primes.html
```

What should I do?

**Comment by mike-huls** [comment]
He Lanskask,
Thanks for the feedback! I'll look into it in the next few days to solve this error. I think the error has something to do with the fact that it tries to clean up code that isn't generated. For example it tries to move an interface file that is not generated because of the `--no-annotations`. A quick fix for now, I guess, would be to either remove `--no-annotations`  or `--no-cleanup`. 

I'll let you know when I've fixed the bug

**Comment by mike-huls** [comment]
Hello @Lanskask 
I've fixed the issue in the newest version of CythonBuilder
Sorry for the delay, I've been busy!
